### ISSUE TITLE
Nothing is working!

### ISSUE THREAD

**Issue by smartpapers** [Vestride/fancy-index#1]
Hello @Vestride 
I tried installing your plugin but Somehow all the styles were not working. It was displaying just like that previous ulgy index thing.
Can you please help me install this?
I wan to install it in a subdirectory (FOLDER) e.g:

www.mysite.com/FOLDER

Please help me. Thank you.

**Comment by glen-cheney** [comment]
Is it only the CSS that's not working? Are you on a Mac? Did you follow [the guide](http://coolestguidesontheplanet.com/get-apache-mysql-php-and-phpmyadmin-working-on-OS X-10-11-el-capitan/) to get it working on your system?

**Comment by smartpapers** [comment]
The styling is not working. It displays as an ugly index directory as usual.
No I'm on windows.
I followed your guide i guess properly. 

One thing that confused me was that i wanted it for a subdirectory but the guide was for the root folder. Alos i don't have a document root thing.

**Comment by glen-cheney** [comment]
I'm not sure if this will work on Windows.

Are you getting a 404 error or any other kind of errors when you open the developer tools?

**Comment by cryptic0** [comment]
@Vestride I think this user is having the same problem as I am.  We are deploying this to a linux apache server.  In my case, the css is not loading.  Not quite sure why.

**Comment by DanDon** [comment]
> @Vestride I think this user is having the same problem as I am. We are deploying this to a linux apache server. In my case, the css is not loading. Not quite sure why.

Same problem here ... doesn't work on Linux Apache running on Ubuntu Server
