### ISSUE TITLE
Replace [order deny,allow Deny form all] with [Require all denied]

### ISSUE THREAD

**Issue by moodboom** [Vestride/fancy-index#17]
I had to make that replacement in .htaccess on apache 2.4.

Thanks for the cool stuff!  Love it.

**Comment by 0x62646f727465** [comment]
@moodboom seems to suggest an update on your .htaccess file. Indeed your file is using Apache 2.2 access control key words where we are using version 2.4 nowadays. 

The consequence seems to be an alert in /var/log/apache2/error.log => AH01630 client by server configuration

**Comment by glen-cheney** [comment]
Fixed by #31. Closing.
