### ISSUE TITLE
Some things aren't displaying correctly

### ISSUE THREAD

**Issue by ghost** [Vestride/fancy-index#2]
I suceffully installed this on my website. It's very beaufiful now, so thank you but the columns titles aren't showing properly and the page title isn't showing, please check it by yourself and apply a fix:
http://dl.hotcube.xyz/

Thanks

-vrack

**Comment by glen-cheney** [comment]
You're missing an image inside the first column. Did you modify the `.htaccess` at all?

**Comment by ghost** [comment]
I just inserted it at the beggining of my other .htaccess that block a lot of countries to access my website (I don't wan't to be visible from the North Corea, xD)
If you wan't to check it: [.htaccess inside this zipped file](dl.hotcube.xyz/htaccess.zip).
Any idea?

**Comment by ghost** [comment]
Any idea?

**Comment by glen-cheney** [comment]
Can you try the `.htaccess` file from this repository without any changes? If that works, then you can start adding your htacess code to that file.

It's been a long time since I've looked at any of the `.htaccess` information.

**Comment by ghost** [comment]
Still the same bug with only your code (original file) and with the other original fancy index files.

**Comment by ghost** [comment]
If the bug can't be fixed, how to remove the first line of the index page?

**Comment by glen-cheney** [comment]
Does 1fc22ee58665b7cdc32004e482ba8ece00209e35 fix your issue?

**Comment by ghost** [comment]
Yah, it fixed it, thanks, and now the icons are appearing into the good line, that's pretty cool, thanks :smiley: 
Now all 's working well (on mobile browser too) :+1:
