### ISSUE TITLE
delete "Index of >>blabla.com<<<" ?

### ISSUE THREAD

**Issue by xeiki** [Vestride/fancy-index#23]
Is there a way that we can delete or hide the subdomain from the title?
But the subfolders names should show up after clicking on the folders?
Is this possible?

for more understanding I did a screenshot for what I mean:
https://s19.directupload.net/images/200125/k3l85ow8.png

thanks.

**Comment by glen-cheney** [comment]
You can comment out this line if you don't want the title to be added:

https://github.com/Vestride/fancy-index/blob/55aef273d8ea1de28877b6334d6683311d46f494/script.js#L191
