### ISSUE TITLE
Deploying on live websites

### ISSUE THREAD

**Issue by cryptic0** [Vestride/fancy-index#7]
I already have a website at say http://example.com hosted from /var/www/html/

If I place a folder called notes inside /var/www/html/notes and clone fancy-index inside notes/, then copied .htaccess from fancy-index to /var/www/html/ and restarted apache, things should start working right?

But they are not.  I also added a staged this folder inside /etc/apache2/apache2.conf as follows:

<Directory /var/www/html/notes>
        AllowOverride All
        Options Indexes MultiViews FollowSymlinks
        Require all granted
</Directory>

Any idea what's going on?

**Comment by glen-cheney** [comment]
That sounds correct to me.

I've only ever used this locally for my Mac, so I'm not sure how it would behave on different systems.

Maybe try quotes around your path? Like in the readme

```apache
<Directory "/var/www/html/notes">
    AllowOverride All
    Options Indexes MultiViews FollowSymLinks
    Require all granted
</Directory>
```

Do you get any errors that you can search the internet for? Maybe a log file has more information.

**Comment by cryptic0** [comment]
Hi Glen,

Thanks for your speedy response.  Strangely enough, fancy-index has started
working mysteriously, albeit not fully, on my end.  Take a look at
http://crypticlineage.net/notes.  The css is now functional, but the
timestamps are all whacky.  Can you direct me to the script that's
controlling the time stamps?

Thanks
Vikram

**Comment by glen-cheney** [comment]
The [`fixTime` method](https://github.com/Vestride/fancy-index/blob/master/script.js#L110) in `script.js` is what changes the time to an "ago" value. If you view the source of the generated index page, you'll notice that the time starts as something like `"2017-10-26 13:14"`. It's possible there's a bug in the small parser I wrote.
