### ISSUE TITLE
decodeURI() titles 

### ISSUE THREAD

**Issue by kaysond** [Vestride/fancy-index#8]
If `window.location.pathname` has URI-encoded components (like `%20` for spaces), then the title comes out quite ugly (and `titleize()`) doesn't work as intended. Using `decodeURI(window.location.pathname.replace(/\/$/g, ''))` solves it.

Personally, I got rid of the `toLowerCase()` `titleize()` altogether.

**Comment by glen-cheney** [comment]
Thanks for pointing this out.

**Comment by kaysond** [comment]
FWIW I think you should also get rid of the `toLowerCase()`. I scanned through a bunch of indexes of media folders, and it looks funny when the function uncapitalizes something because it's in the middle of a word or next to a non space character. If you remove the lower case, it will still capitalize everything next to a space hyphen underscore, etc. but will leave existing capitals untouched.

Not sure what your intended behavior/typical scenario is. It's not hard for users to change, in any case.

**Comment by kaysond** [comment]
Btw thanks for putting this together I'd been looking for a responsive index for years
